### ISSUE TITLE
account for offset?

### ISSUE THREAD

**Issue by tomjohnson1492** [ghiculescu/jekyll-table-of-contents#10]
I love the plugin. One issue. I have a fixed floating header. As a result, the links in the toc jump to the wrong spot. I need to offset it by about 20 px. Any idea how I do that?

**Comment by ghiculescu** [comment]
After setting up the toc initially, some code like this should do what you want. It overrides the browser default and instead scrolls down an extra 20 pixels.

````javascript
$('.toc').on('click', 'a', function() {
  var target = $(this.getAttribute('href'))
    , scroll_target = target.offset().top

  $(window).scrollTop(scroll_target - 20);
  return false
})
````

**Comment by tomjohnson1492** [comment]
Awesome! Thanks so much for helping me.

**Comment by tomjohnson1492** [comment]
I couldn't quite get the offset to work using this script. I ended up using this stackoverflow css trick: http://stackoverflow.com/a/12606867/4251438

**Comment by tomjohnson1492** [comment]
You know what -- I ended up switching around my theme, and ran into this same problem. So I used your code and it worked extremely well (though I used 70 instead of 20). Thanks again.

**Comment by ghiculescu** [comment]
No worries. You'll just want to change that number to the size of your fixed header :)
