### ISSUE TITLE
Compatible with pandoc?

### ISSUE THREAD

**Issue by chepec** [ghiculescu/jekyll-table-of-contents#11]
Trying to enable this on my Jekyll site (self-hosted, not github pages).
I am not entirely sure I understood the instructions, so I tried to put the `<div>` and `<script>` tags in a few different places (I know, total noob) but it seemed to have no effect.

So I wonder, does the fact that I use pandoc markdown affect anything? Should I add something to `extensions` in my `_config.yml`?

This is the relevant section of my current `_config.yml`:

    markdown: pandoc
    pandoc:
       extensions:
       - smart
       - mathjax

In `_layouts/default.html`, I have (only showing the header here):

    <head><script type="text/javascript" src="/js/toc.js"></script></head>

and in `_layouts/post.html`, this is the code inside the `<article>` tag:

    <article class="post-content">
    <div id="toc">
    <script type="text/javascript">
       $(document).ready(function() {
          $('#toc').toc();
       });
    </script>
    </div>
    {{ content }}
    </article>

Have I put the TOC code in the right places? Not even close?

**Comment by eksperimental** [comment]
this plugin doesn't care how the html is generated (whether you use pandoc or jekyll or you code your html by hand)

what you need is a heading element with an id, 

your code is alright, but ideally, first you want to load the page in the browser, and after that, build the TOC.
place  `<div id="toc"></div>` wherever you want the TOC to be.

and you can place the rest at the bottom of your page, before closing your body tag,

```html
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="toc.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript">
    $(document).ready(function() {
      $('#toc').toc({
      listType: 'ol',
      });
    });
    </script>  
```

that will speed up the execution in slow conections, because users will still be able to read the page as it is being loaded the external scripts

**Comment by ghiculescu** [comment]
What @eksperimental said. It would be good if you could show the full html of your page so we can check that the headers have IDs.

**Comment by chepec** [comment]
@eksperimental Thanks for your kind pointers. You got me on the right track! I have it working now.
@ghiculescu Better late than never :) 
For future reference, I got the following setup now:
Put the `toc.js`into my site root, like so: `/js/toc.js`.
In `/_layouts/default.html`, placed the script calls before the closing body tag

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="/js/toc.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript">
       $(document).ready(function() {
          $('#toc').toc({
	     listType: 'ul',
	   });
        });
    </script>

And in `/_layouts/post.html`, I placed the div tag before the main body of the post, but below its title.

    <article class="post-content">
    <div id="toc"></div>
    {{ content }}
    </article>

I don't remember what exactly changed in my setup since my first try, but I think I was missing the first javascript call to jquery. Thanks for the help.

**Comment by ghiculescu** [comment]
:+1:
