### ISSUE TITLE
Add jQuery as a dependency in the documentation

### ISSUE THREAD

**Issue by tomjohnson1492** [ghiculescu/jekyll-table-of-contents#13]
Can you add that jQuery is a dependency for this script to work? 

Somewhere in the Jekyll project, a user should reference jQuery -- e.g., 

```
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
```

**Comment by ghiculescu** [comment]
This is mentioned in the Basic Usage section, though there isn't a code snippet because there's plenty of different ways to reference jQuery - use whichever floats your boat.
