### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by dannguyen** [ghiculescu/jekyll-table-of-contents#14]
Didn't have time to make a legit pull request at the moment, but just wanted to say *Thanks!*...it's great when someone else on the Internet has anticipated exactly what I need (a way to do TOC when kramdown won't do and plugins are disabled) and has made it *just work*.

**Comment by dannguyen** [comment]
And great effort in the documentation, even though the plugin is so straightforward to use.

**Comment by ghiculescu** [comment]
:) Thank you!
