### ISSUE TITLE
Add option to add classes to list elements

### ISSUE THREAD

**Issue by caesarivs** [ghiculescu/jekyll-table-of-contents#15]
I would like to add bootstrap classes to style the \<ul\>, \<ol\>, and \<li\> elements, and it would be nice if there was some sort of option so you could call the toc() function with a classes parameter for \<ul\> or \<ol\> elements, accordint to listType parameter, something like:

```js
$('#toc').toc({
    listType: 'ul', // values: [ol|ul]
    classes: 'nav, nav-stacked',
});
```

So the \<ul\> element has the appearence of nav-stacked elements according to bootstrap

**Comment by ghiculescu** [comment]
Could I tempt you to submit a pull request?

**Comment by caesarivs** [comment]
I just hardcoded them into my project, I'm not proficient in JavaScript so that's why I made the suggestion

**Comment by nscyclone** [comment]
I think that this issue can be closed now.
