### ISSUE TITLE
rdiscount generate TOC with the same id for all headers

### ISSUE THREAD

**Issue by lengerfulluse** [ghiculescu/jekyll-table-of-contents#16]
I use rdiscount to generate toc, with configuration:

    markdown: rdiscount
    rdiscount:
        extensions:
          - generate_toc

I just found that it generated the same id for all header tags(h4, h5, ...). for example:  
<img width="421" alt="screen shot 2015-07-27 at 5 30 30 pm" src="https://cloud.githubusercontent.com/assets/1578404/8902691/4799728e-3485-11e5-8309-10a2c93473bc.png">

which makes all the toc navigate links to the same place. Anyone encounter the same issue?

**Comment by ghiculescu** [comment]
Closing unless someone else has seen this come up...
